'''
This files verify the intregrity of data generated by the simulation in following ways
1. Check for any missing data and cross verify all the data across all three folder : Lidar, tracking and samples.
'''

import pandas as pd
import os
import tqdm

HOME = os.environ['HOME']

lpath = f'{HOME}/webots_code/data/traffic_test/high/lidar_samples'
gpath = f'{HOME}/webots_code/data/traffic_test/high/samples'
tpath = f'{HOME}/webots_code/data/traffic_test/high/tracking'

removed = 0
samples = 0
lidar = list()
for i in (os.listdir(gpath)):
    try:
        df = pd.read_pickle(gpath+'/'+i)
        lost = list()

        for j in range(len(df)):
            if not(df.at[j,'Lidar'] in os.listdir(lpath)):
                lost.append(j)
            else:
                lidar.append(df.at[j,'Lidar'])
        
        removed+=len(lost)
        if len(lost)!=0:
            print(lost)
            break
        samples+=len(df)
    except:
        print(i)

print(samples)

l_del = 0
for i in os.listdir(lpath):
    if not(i in lidar):
        os.remove(lpath+'/'+i)
        l_del+=1
print(l_del)

